# Generated by Django 4.2.11 on 2024-04-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="explain",
            field=models.TextField(blank=True, null=True),
        ),
    ]
